export { CoursesPage } from "./CoursesPage";
export { CourseDetailsPage } from "./CourseDetailsPage";
export { SignUpPage } from "./SignUpPage";
export { SignInPage } from "./SignInPage";
export { NotFoundPage } from "./NotFoundPage";
export { ForbiddenPage } from "./ForbiddenPage";
export { ErrorPage } from "./ErrorPage";
export { CreateCoursePage } from "./CreateCoursePage";
export { UpdateCoursePage } from "./UpdateCoursePage";
